# Generated by Django 3.0.6 on 2020-05-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
    ]
